In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, HTML
import sklearn.preprocessing as prep
import math

## Reading in of data & preprocessing

In [3]:
data = pd.read_csv("data/zip.train", header=None, sep=" ")
data = data.iloc[:,0:-1] # last column (NaN) is deleted
scaler = prep.MinMaxScaler()
norm_data = data.copy() # copy ist notwendig, andernfalls wird data mit den folgenden Zeilen auch geÃ¤ndert!
norm_data.iloc[:,1:] = scaler.fit_transform(norm_data.iloc[:,1:]) # data is transformed to range from 0-1 for each row (only cols 1:end)
#MinMaxScaler: see http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
display(data.head())
display(norm_data.head())
zstand_scaler = prep.StandardScaler()
zstand_data = data.copy()
zstand_data.iloc[:,1:] = zstand_scaler.fit_transform(zstand_data.iloc[:,1:])
display(zstand_data.head())

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,6.0,-1.0,-1.0,-1.0,-1.000,-1.000,-1.000,-1.000,-0.631,0.862,...,0.304,0.823,1.000,0.482,-0.474,-0.991,-1.000,-1.000,-1.000,-1.0
1,5.0,-1.0,-1.0,-1.0,-0.813,-0.671,-0.809,-0.887,-0.671,-0.853,...,-0.671,-0.671,-0.033,0.761,0.762,0.126,-0.095,-0.671,-0.828,-1.0
2,4.0,-1.0,-1.0,-1.0,-1.000,-1.000,-1.000,-1.000,-1.000,-1.000,...,-1.000,-1.000,-1.000,-0.109,1.000,-0.179,-1.000,-1.000,-1.000,-1.0
3,7.0,-1.0,-1.0,-1.0,-1.000,-1.000,-0.273,0.684,0.960,0.450,...,-0.318,1.000,0.536,-0.987,-1.000,-1.000,-1.000,-1.000,-1.000,-1.0
4,3.0,-1.0,-1.0,-1.0,-1.000,-1.000,-0.928,-0.204,0.751,0.466,...,0.466,0.639,1.000,1.000,0.791,0.439,-0.199,-0.883,-1.000,-1.0

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,6.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.1845,0.9310,...,0.6520,0.9115,1.0000,0.7410,0.2630,0.0045,0.0000,0.0000,0.000,0.0
1,5.0,0.0,0.0,0.0,0.0935,0.1645,0.0955,0.0565,0.1645,0.0735,...,0.1645,0.1645,0.4835,0.8805,0.8810,0.5630,0.4525,0.1645,0.086,0.0
2,4.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.4455,1.0000,0.4105,0.0000,0.0000,0.000,0.0
3,7.0,0.0,0.0,0.0,0.0000,0.0000,0.3635,0.8420,0.9800,0.7250,...,0.3410,1.0000,0.7680,0.0065,0.0000,0.0000,0.0000,0.0000,0.000,0.0
4,3.0,0.0,0.0,0.0,0.0000,0.0000,0.0360,0.3980,0.8755,0.7330,...,0.7330,0.8195,1.0000,1.0000,0.8955,0.7195,0.4005,0.0585,0.000,0.0

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,6.0,-0.069284,-0.124758,-0.199991,-0.311415,-0.450697,-0.619879,-0.881319,-0.761770,1.214779,...,0.650258,0.907355,1.166749,1.096857,0.308508,-0.369357,-0.258657,-0.186315,-0.130262,-0.080576
1,5.0,-0.069284,-0.124758,-0.199991,0.207321,0.203867,-0.316062,-0.723494,-0.813836,-1.062997,...,-0.611320,-1.076886,-0.197335,1.481256,2.430343,2.324689,2.749895,1.252351,0.951586,-0.080576
2,4.0,-0.069284,-0.124758,-0.199991,-0.311415,-0.450697,-0.619879,-0.881319,-1.242082,-1.258234,...,-1.037022,-1.513844,-1.474266,0.282593,2.838916,1.589072,-0.258657,-0.186315,-0.130262,-0.080576
3,7.0,-0.069284,-0.124758,-0.199991,-0.311415,-0.450697,0.536536,1.470694,1.309167,0.667581,...,-0.154564,1.142436,0.554034,-0.927092,-0.594473,-0.391064,-0.258657,-0.186315,-0.130262,-0.080576
4,3.0,-0.069284,-0.124758,-0.199991,-0.311415,-0.450697,-0.505351,0.230440,1.037121,0.688832,...,0.859874,0.662977,1.166749,1.810543,2.480127,3.079601,2.404160,0.325308,-0.130262,-0.080576

## Looking at one example image

In [ ]:
example_image = pd.DataFrame(norm_data.iloc[1,1:]) # select row 2 of the dataframe, columns 1 to end
print(example_image.shape) # show shape of image
example_image_reshaped = example_image.values.reshape(16,16)

In [ ]:
plt.imshow(example_image_reshaped,cmap="jet",interpolation="nearest")
plt.show

## Useful functions

In [ ]:
def get_digit_rows(data,digit): 
    """returns all rows of a given digit
        careful: first column (target digit) still included!!!"""
    rows = data[data[0] == float(digit)]
    return pd.DataFrame(rows)

#display(get_digit_rows(norm_data,2)) # testing the function

def print_image_observation(data,row):
    """shows the image of a specific row in data"""
    img = data.iloc[row,1:].values.reshape(16,16)  
    plt.imshow(img,cmap="jet",interpolation="nearest",vmin=0,vmax=1)
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.tight_layout()
    return None
   
print_image_observation(norm_data,3637)

def get_digit_stat_array(data,digit,stat):
    """returns the (reshaped) 16x16 image for a given digit and statistic"""
    digit_rows = get_digit_rows(data,digit).iloc[:,1:]
    if stat == "mean":
        stat_row = digit_rows.mean()
    elif stat == "sd":
        stat_row = np.std(digit_rows)
    elif stat == "max":
        stat_row = np.max(digit_rows)
    elif stat == "min":
        stat_row = np.min(digit_rows)
    else: print("please enter a valid stat (mean,sd,max or min)")
    img = stat_row.values.reshape(16,16)
    return img

#display(get_digit_stat_array(norm_data,8,"mean")) # testing the function

def print_digit(data,digit,stat):
    """returns a plot showing the digit image statistic, e.g. average digit image
        colormap ranges from 0 to 1"""
    img = get_digit_stat_array(data,digit,stat)
    plt.imshow(img,cmap="jet",interpolation="nearest",vmin=0,vmax=1)
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.tight_layout()
    

#print_digit(norm_data,4,"mean") # testing the function

## Extracting stat images for all numbers & showing them all in a plot

In [ ]:
fig=plt.figure(figsize=(15, 15))
columns = 5
rows = 2
for i in range(0, columns*rows):
    fig.add_subplot(rows, columns, i+1)
    print_digit(norm_data,i,"sd") # possible values for stat: "mean", "sd", "max", "min"

## Combining mean and sd image to build a 'predictive image' for each digit

In [ ]:
fig=plt.figure(figsize=(20, 20))
columns = 5
rows = 2
for i in range(0, columns*rows):
    fig.add_subplot(rows, columns, i+1)
    img_sd = get_digit_stat_array(norm_data,i,"sd")
    img_mean = get_digit_stat_array(norm_data,i,"mean")
    img_combi = img_mean/(img_sd+0.00000000000000000000001) # yes, this is not ideal :D solutions for avoiding div by zero needed
    plt.imshow(img_combi,cmap="jet",interpolation="nearest",vmin=0,vmax=1)
    plt.colorbar(fraction=0.046, pad=0.04)
    plt.tight_layout()
plt.show()

## Summaries for each digit: mean, max, min, sd, number of observations

In [ ]:
## For calculation of mean, max, min the mean array is used. For sd, the sd array is used. 
#NrObs = Number of observations for each digit

vals = np.zeros((5,10)) #creating an empty np_array
stats_df = pd.DataFrame(data=vals,columns = [0,1,2,3,4,5,6,7,8,9],index = ["Mean","Max","Min","SD","NrObs"])
for j in range(0,10):
    meanrow = get_digit_stat_array(norm_data,j,"mean") # mean image for each digit
    sdrow = get_digit_stat_array(norm_data,j,"sd")
    meanval = np.mean(meanrow)
    maxval = np.max(meanrow)
    minval = np.min(meanrow)
    sdval = np.mean(sdrow) # the mean of the sd image --> average sd
    stats_df.loc['Mean',j] = meanval 
    stats_df.loc['Max',j] = maxval
    stats_df.loc['Min',j] = minval
    stats_df.loc['SD',j] = sdval
    stats_df.loc['NrObs',j] = get_digit_rows(norm_data,j).shape[0]
display(stats_df)

## Identifying and removing outliers

In [ ]:
def outside_boundaries(myseries,lower,upper):
    """returns the number of elements of myseries which are outside the lower-upper range (lower and upper are also series)"""
    within_lims = myseries.between(lower,upper,inclusive=True)
    return myseries.shape[0] - sum(within_lims)

def identify_outlier_rows(data,digit,limit):
    """returns the image rows (=observations) for each digit which are very different from the other image rows. 
    Identifies image rows of a digit, where more than limit * pixels (limit ranges between 0 and 1) are outlier 
    pixels (outlier pixel = outside mean +- 2sd image values). E.g. if limit = 0.1 --> observations are identified 
    as outliers if 0.1 * 256 pixels are outside the mean +- 2sd range"""
    all_rows = get_digit_rows(norm_data,digit).iloc[:,1:]
    nr_observations = all_rows.shape[0]
    nr_limit_pixels = limit * 256
    print(f"Nr of observations: {nr_observations}")
    print(f"If an observation (= a row of data) has more than {nr_limit_pixels} outlier pixels, it is identified as outlier observation")
    all_rows.columns = range(all_rows.shape[1]) # colnames mÃ¼ssen geÃ¤ndert werden, damit sie wieder von 0 bis ende gehen (statt bei 1 anzufangen)!
    all_rows.index = range(nr_observations) 
    #display(all_rows)      
    mean_array = get_digit_stat_array(norm_data,digit,"mean")
    sd_array = get_digit_stat_array(norm_data,digit,"sd")
    upper_lim = pd.Series((mean_array + 2*sd_array).flatten()) # .flatten() and pd.Series reconvert the 16*16 array to a 256 Series
    lower_lim = pd.Series((mean_array - 2*sd_array).flatten())
    digit_nr_outlier_pixels = pd.Series(np.zeros(nr_observations))
    for index,row in all_rows.iterrows():
        digit_nr_outlier_pixels[index] = outside_boundaries(row,lower_lim,upper_lim) 
    #print(f"Number of outlier pixels for each of the {nr_observations} observations: ")
    #display(digit_nr_outlier_pixels)
    which_row_is_outlier = digit_nr_outlier_pixels.gt(nr_limit_pixels)
    print(f"{sum(which_row_is_outlier)} outlier observations were identified for this digit.")
    infodf = pd.concat([lower_lim,pd.Series(mean_array.flatten()),upper_lim,all_rows.transpose()],axis=1)
    #with pd.option_context('display.max_rows', None, 'display.max_columns', 10): # shows the whole df 
        #display(infodf)
    return all_rows.loc[which_row_is_outlier]


display(identify_outlier_rows(norm_data,1,0.2))

In [ ]:
import math # fÃ¼rs aufrunden math.ceil

#### schneller machen! dauert ewig

def print_outlier_images(data,digit,limit):
    """returns a plot showing the digit outlier observations for the chosen limit (limit ranges from 0-1). E.g. 
        if limit = 0.1, then an observation is considered as outlier if more than 256*0.1 = 25.6 pixels are outside 
        the mean +-2sd range. (I.e., the larger the limit, the less outliers are identified)"""
    fig = plt.figure(figsize=(15,15))
    ax = []
    rows = identify_outlier_rows(data,digit,limit) #dataframe with index = rownr in get_digit_rows
    display(rows)
    columns_figure = 5
    if not rows.empty:
        rows_figure = math.ceil(rows.shape[0]/columns_figure)
    else: return print("No outliers were found!")
    if rows.shape[0] > 50:
        print(f"There are {rows.shape[0]} outliers! Surely you don't want to see them all...")
        return None
    else:
        for i in range(0, rows.shape[0]):
            ax.append(fig.add_subplot(rows_figure, columns_figure, i+1))
            img = rows.iloc[i,:].values.reshape(16,16)
            indexlabel = rows.iloc[i].name
            datarow = get_digit_rows(norm_data,digit).iloc[indexlabel].name #finding the index of the row in the original data dataframe
            ax[i].set_title(f"data[{datarow}]")
            plt.imshow(img,cmap="jet",interpolation="nearest",vmin=0,vmax=1)
        plt.colorbar(fraction=0.046, pad=0.04)
        plt.tight_layout()
        plt.show()

print_outlier_images(norm_data,0,0.15)

In [ ]:
# testing the .flatten() function
# not important for analysis, just a check

mean_3 = get_digit_stat_array(norm_data,3,"mean")
vector_mean_3_flattened = pd.Series(mean_3.flatten())
data_3 = get_digit_rows(norm_data,3).iloc[:,1:]
vector_mean_3 = data_3.mean()
vector_mean_3.index = range(vector_mean_3.shape[0])
both = pd.concat([vector_mean_3_flattened,vector_mean_3],axis=1)
#display(both)

# Clustering

In [ ]:
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

In [ ]:
#label_df[label_df["Target"] == 0].groupby("KMeans")["Target"].count()

In [ ]:
def run_cluster_analysis(prep_data):
    """does not use the first ([0]) column of prep_data!! (target col)"""
    K = KMeans(n_clusters = 10).fit(prep_data.iloc[:,1:])
    K_labels_nr = K.labels_
    G = GaussianMixture(n_components = 10, n_init = 3).fit(prep_data.iloc[:,1:])
    G_labels_nr = G.predict(prep_data.iloc[:,1:])
    K_labels = [["A","B","C","D","E","F","G","H","I","J"][nr] for nr in K_labels_nr]
    G_labels = [["A","B","C","D","E","F","G","H","I","J"][nr] for nr in G_labels_nr]
    label_df = pd.concat([norm_data.iloc[:,0],pd.Series(K_labels),pd.Series(G_labels)],axis=1)
    label_df.columns = ["Target","KMeans","Gaussian"]
    label_df.Target = label_df.Target.astype(int)
    display(label_df.head())
    return [K,G,label_df]



def make_barplot(method,res):
    [result_df_scaled_tar,result_df_scaled_clust,corr] = calculate_correct_rates(method,res);
    result_df_scaled_tar.plot.bar(figsize=(20,8),title = method)
    result_df_scaled_clust.T.plot.bar(figsize=(20,8),title = method)
    

def get_clust_rows(data,method,cluster,res):
    """returns the rows for a certain cluster and method (KMeans or Gaussian)"""
    label_df = res[2]
    cluster_rows = data[label_df[method] == cluster]
    return cluster_rows.iloc[:,1:]

def get_stat_array(data_rows,stat,res):
    """returns the (reshaped) 16x16 image for given rows (256 cols) and statistic"""
    if stat == "mean":
        stat_row = data_rows.iloc[:,0:256].mean()
    elif stat == "median":
        stat_row = data_rows.iloc[:,0:256].median()
    else: print("please enter a valid stat (mean or median)")
    img = stat_row.values.reshape(16,16)
    return img

def get_stat_array_reduced(data_rows,stat,res):
    """returns the (reshaped) 4x4 image for given rows (16 cols) and statistic"""
    if stat == "mean":
        stat_row = data_rows.iloc[:,0:16].mean()
    elif stat == "median":
        stat_row = data_rows.iloc[:,0:16].median()
    else: print("please enter a valid stat (mean or median)")
    img = stat_row.values.reshape(4,4)
    return img

def print_subplots_all_clusters(data,method,stat,res):
    clusters = ["A","B","C","D","E","F","G","H","I","J"]
    ncols = 5
    nrows = math.ceil(len(clusters)/2)
    fig = plt.figure(figsize = (20,20)) 
    for clust in clusters:
        rows = get_clust_rows(data,method,clust,res)
        stat_img = get_stat_array(rows,stat,res)
        #print(rows)
        plt.subplot(nrows,ncols,clusters.index(clust)+1)
        plt.title(clust,fontsize = 25)
        plt.imshow(stat_img, cmap='hot', interpolation='none',vmin=-1,vmax=1)
        plt.colorbar(fraction=0.046, pad=0.04)
    plt.suptitle(method, fontsize=30,y=1.03)
    #plt.subplots_adjust(wspace=0.05)
    plt.tight_layout()
    plt.show()
    return None
 
def print_subplots_all_clusters_reduced(data,method,stat,res):
    clusters = ["A","B","C","D","E","F","G","H","I","J"]
    ncols = 5
    nrows = math.ceil(len(clusters)/2)
    fig = plt.figure(figsize = (20,20)) 
    for clust in clusters:
        rows = get_clust_rows(data,method,clust,res)
        stat_img = get_stat_array_reduced(rows,stat,res)
        #print(rows)
        plt.subplot(nrows,ncols,clusters.index(clust)+1)
        plt.title(clust,fontsize = 25)
        plt.imshow(stat_img, cmap='hot', interpolation='none',vmin=-1,vmax=1)
        plt.colorbar(fraction=0.046, pad=0.04)
    plt.suptitle(method, fontsize=30,y=1.03)
    #plt.subplots_adjust(wspace=0.05)
    plt.tight_layout()
    plt.show()

def calculate_correct_rates(method,res):
    """calculates the correctrate (as nr recognized / total nr target) for each target digit
    and the average error rate for all digits. Returns: dataframes with proportions of 
    targets ("res..clust": nr target observations/nr all observations in cluster. 
    "res..tar": nr target observations in cluster / total nr target obs); the correctrates
    if a target is split in two clusters (e.g. 0), the cluster with the highest proportion of target is 
    selected. if two targets are merged in one cluster, the target with highest prop in the cluster
    is chosen for this cluster. Other target is counted as 0% recognized
    """
    bar_data = pd.DataFrame(data = np.zeros((10,10)),columns=["A","B","C","D","E","F","G","H","I","J"])
    label_df = res[2]
    for digit in range(0,10):
        temp_result = label_df[label_df["Target"] == digit].groupby(method)["Target"].count()
        #print((temp_result))
        clusters_keys = temp_result.keys()
        #print([clusters_keys])
        for cluster_idx in [clusters_keys]:
            bar_data.loc[digit,cluster_idx] = temp_result[cluster_idx]
    result_df_scaled_tar = bar_data.divide(bar_data.sum(1), axis=0)
    result_df_scaled_clust = bar_data.divide(bar_data.sum(0), axis=1)
    #cluster_names = ["A","B","C","D","E","F","G","H","I","J"]
    clust_labels_real_names = []
    # finding the real name for each cluster (in res...clust)
    for clust in list(result_df_scaled_clust.columns):
        #ix = cluster_names.index(clust)
        clust_labels_real_names.append(np.where(result_df_scaled_clust[clust] == result_df_scaled_clust[clust].max())[0][0])
        #print(type(clust_labels_real_names))
    labelcomp_df = pd.DataFrame({method+"label": result_df_scaled_clust.columns,"recognized as": clust_labels_real_names})
    #display(clust_labels_real_names)
    display(labelcomp_df)
    nr_recogn = labelcomp_df.groupby("recognized as").count()
    display(nr_recogn)
    # some clusters have the same real name. finding these and deciding for one of the clusters
    # by choosing the cluster which identified the real digit more often. e.g. if real target digit 0 is
    # contained more often in cluster B than in H, cluster B is chosen
    split_tars = list(nr_recogn[nr_recogn[method+"label"] > 1].index)
    display(split_tars) # for example series including 0 and 1 (if they are both
                                #split to several clusters)
    double_clust = labelcomp_df[method+"label"][labelcomp_df["recognized as"].isin(split_tars)]
    print(f"double_clust: {double_clust},{double_clust.shape}")
    winner_clust,other_clust= [],[]
    for star in split_tars: # runs through all split targets and finds the cluster 
        #with the highest proportion of this target
        winner = result_df_scaled_clust.iloc[star].idxmax(axis = 1)
        winner_clust.append(winner)
        others = double_clust[double_clust!=winner].tolist()
        other_clust.append(others)
        print("winner_clust:")
        display(winner_clust)
        print(f"other_clust: {other_clust}")
    if other_clust:
        unique_mapping = labelcomp_df[~labelcomp_df[method+"label"].isin(other_clust[0])]
    else:
        unique_mapping = labelcomp_df.copy()
    #display(unique_mapping)
    #new_label_names = pd.Series(label_df[method].replace(list(unique_mapping[method+"label"]),
                                                         #unique_mapping["recognized as"]))
    #new_label_names.rename(method + "_guess",inplace = True)
    #display(new_label_names)
    #label_df_new = pd.concat([label_df,new_label_names],axis=1)
    corr_rates = pd.DataFrame(data = np.zeros((11,1)),columns = [method + "label_correct"])
    for digit in range(0,10):
        corresponding_cluster = unique_mapping[method+"label"][unique_mapping["recognized as"] == digit]
        corr_rate= list(result_df_scaled_tar.loc[digit,corresponding_cluster])
        if corr_rate:
            corr_rates.iloc[digit] = corr_rate[0]
        else: corr_rates.iloc[digit] = 0
    corr_rates.iloc[10] = corr_rates.loc[0:9,method+"label_correct"].mean()
    corr_rates.rename(index={10: "Total correct"},inplace=True)
    
    return [result_df_scaled_tar,result_df_scaled_clust,corr_rates]
    
    

#display(calculate_correct_rates("Gaussian",res3)[2])

## Clustering mit Original Data

In [ ]:
data.head()

In [ ]:
res1 = run_cluster_analysis(data)

In [ ]:
#res1 = res

In [ ]:
make_barplot("KMeans",res1)
make_barplot("Gaussian",res1)
print_subplots_all_clusters(data,"KMeans","mean",res1)
print_subplots_all_clusters(data,"Gaussian","mean",res1)

In [ ]:
orig_K = display(calculate_correct_rates("KMeans",res1)[2])
orig_G = display(calculate_correct_rates("Gaussian",res1)[2])

## Clustering mit neighboring info

In [ ]:
from skimage import transform

def add_neighbor_info(data):
    """does not take into account col 1 of data!!!
    creates new dataframe containing 16 additional columns with the local means of 4x4 imgs"""
    x = []
    for i in range(len(data)):
        img = pd.DataFrame(data.iloc[i,1:]).values.reshape(16,16)
        downscaled_img = transform.downscale_local_mean(img,(4,4)).flatten()
        x.append(downscaled_img)
    new_data = data.reset_index().iloc[:,1:]
    test3 = pd.concat([new_data,pd.DataFrame(x)],axis=1)
    test3.columns = range(test3.shape[1])
    return pd.DataFrame(test3)

In [ ]:
nb_data = add_neighbor_info(data)
nb_data.head()

data.head()

In [ ]:
res2 = run_cluster_analysis(nb_data)

In [ ]:
make_barplot("KMeans",res2)
make_barplot("Gaussian",res2)
print_subplots_all_clusters(nb_data,"KMeans","mean",res2)
print_subplots_all_clusters(nb_data,"Gaussian","mean",res2)

In [ ]:
nb_K = display(calculate_correct_rates("KMeans",res2)[2])
nb_G = display(calculate_correct_rates("Gaussian",res2)[2])

## Clustering nur mit neighboring info

In [ ]:
nb_data_reduced_vals = nb_data.iloc[:,257:273]
nb_data_reduced_tars = nb_data.iloc[:,0]
#display(pd.DataFrame(nb_data_reduced_tars))

nb_data_reduced = pd.concat([nb_data_reduced_tars,nb_data_reduced_vals],axis=1)
#print(nb_data_reduced.shape)
nb_data_reduced.columns = range(nb_data_reduced.shape[1])
nb_data_reduced.head()

In [ ]:
res3 = run_cluster_analysis(nb_data_reduced)

In [ ]:
make_barplot("KMeans",res3)
make_barplot("Gaussian",res3)
print_subplots_all_clusters_reduced(nb_data_reduced,"KMeans","mean",res3)
print_subplots_all_clusters_reduced(nb_data_reduced,"Gaussian","mean",res3)

In [ ]:
print_subplots_all_clusters(nb_data,"KMeans","mean",res3)
print_subplots_all_clusters(nb_data,"Gaussian","mean",res3)

In [ ]:
nb_reduced_K = display(calculate_correct_rates("KMeans",res3)[2])
nb_reduced_G = display(calculate_correct_rates("Gaussian",res3)[2])

# Clustering nach Multiplikation mit neighbouring info

In [ ]:
from skimage.util.shape import view_as_blocks
#http://scikit-image.org/docs/dev/api/skimage.util.html?highlight=view_as_windows#skimage.util.view_as_windows
data_array = np.array(data.copy())
data_array[:,1:].shape
len(data_array)

In [ ]:
multip_data_arr = np.zeros((len(data_array),256))
for i in range(len(data_array)): # iterates over rows of data
    img_row = data_array[i,1:].reshape(16,16)
    B = view_as_blocks(img_row, block_shape=(4, 4)).reshape(16,4,4)
    #print(B.shape[0])
    #print(B.reshape(16,4,4))
    multip_block_row = np.zeros((16,16))
    for j in range(B.shape[0]): # for the 16 blocks..
        #print(block.mean())
        multip_block_row[j] = np.multiply(B[j,:,:],B[j,:,:].mean()).flatten()
        #print(multip_block_row[j])
    
    multip_data_arr[i] = multip_block_row.flatten()
        
multip_df_no_tars = pd.DataFrame(data = multip_data_arr)
multip_data = pd.concat([data.iloc[:,0],multip_df_no_tars],axis=1)

multip_data.columns = range(multip_data.shape[1])
multip_data.head()

In [ ]:
with pd.option_context('display.max_rows', 10, 'display.max_columns', None): # shows the whole df 
    display(multip_data)

In [ ]:
plt.subplot(1,2,1)
print_image_observation(norm_data,0)
plt.subplot(1,2,2)
print_image_observation(multip_data,0)

In [ ]:
res4 = run_cluster_analysis(multip_data)

In [ ]:
make_barplot("KMeans",res4)
make_barplot("Gaussian",res4)
print_subplots_all_clusters(multip_data,"KMeans","mean",res4)
print_subplots_all_clusters(multip_data,"Gaussian","mean",res4)

In [ ]:
nb_multip_K = display(calculate_correct_rates("KMeans",res4)[2])
nb_multip_G = display(calculate_correct_rates("Gaussian",res4)[2])

# Comparing the correct rates

In [ ]:
def show_all_correct_rates(res_list):
    #analyses_names = ["orig_data","nb"]
    analyses_names = ["orig_data","nb","nb_reduced","nb_multip"]
    rates = []
    
    for r in res_list:
        rates.append(calculate_correct_rates("KMeans",r)[2])
        rates.append(calculate_correct_rates("Gaussian",r)[2])
    #cols = [item + "\n" + other for item in analyses_names for other in ["KMeans","Gaussian"]]
    hierarch_names = [analyses_names,["KMeans","Gaussian"]]
    rates_df = pd.concat(rates,axis = 1)
    fancy_idx = pd.MultiIndex.from_product(hierarch_names)
    #rates_df.columns = cols
    rates_df.columns = fancy_idx
    display(rates_df)
    print(f"fancy idx: {fancy_idx.get_level_values}")
    print(rates_df.columns)
    rates_df.loc["Total correct"].unstack(1).plot(y= ["KMeans","Gaussian"],kind='bar',figsize=(20,8),rot=0,ylim=(0,1),title = "Barplot Analyses Comparison",fontsize=20)
    print(rates_df.unstack(1).index.get_level_values(0))
    
show_all_correct_rates([res1,res2,res3,res4])